In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
#Sentences

sent = [    'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I am a good developer',
        'understand the meaning of words',
        'your videos are good']

In [6]:
# Define the vocabulary size

voc_size = 10000

In [7]:
# One hot Representation 
one_hot_rep = [one_hot(words,voc_size) for words in sent]


In [8]:
one_hot_rep

[[7422, 3040, 8833, 2940],
 [7422, 3040, 8833, 5200],
 [7422, 5326, 8833, 6682],
 [150, 5140, 1093, 2947, 8151],
 [150, 5140, 1093, 2947, 1875],
 [9964, 7422, 8448, 8833, 6420],
 [429, 89, 1138, 2947]]

In [16]:
#Word Embedding representation
from tensorflow.keras.layers import Embedding,Input
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
sent_len = 5
embedded_doc = pad_sequences(one_hot_rep,padding='pre',maxlen=sent_len)
print(embedded_doc)

[[   0 7422 3040 8833 2940]
 [   0 7422 3040 8833 5200]
 [   0 7422 5326 8833 6682]
 [ 150 5140 1093 2947 8151]
 [ 150 5140 1093 2947 1875]
 [9964 7422 8448 8833 6420]
 [   0  429   89 1138 2947]]


In [12]:
#Feature representation
dim = 10


In [17]:
model = Sequential()
model.add(Input(shape=(sent_len,)))
model.add(Embedding(voc_size,dim,input_length=sent_len))
model.compile('adam','mse')

/Users/phupwinteaindray/miniconda3/lib/python3.13/site-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [18]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 5, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step


array([[[-0.03817686, -0.02731646, -0.03528111,  0.03071573,
          0.03480065,  0.02348955, -0.00513406,  0.02617281,
         -0.02690274, -0.04256693],
        [-0.03195091,  0.0028404 ,  0.02852453,  0.0188711 ,
          0.03225197,  0.01196315, -0.01414931,  0.04771825,
          0.01205415, -0.01610284],
        [ 0.0367745 , -0.00819444, -0.01433142,  0.00480877,
         -0.01347567,  0.02767954,  0.01406113, -0.04667852,
          0.03095111, -0.0049703 ],
        [ 0.01482698, -0.02923012, -0.00779319,  0.03997023,
          0.00158872,  0.01083321, -0.03187507, -0.03761039,
         -0.03727875, -0.02228194],
        [-0.0449848 , -0.01131218,  0.00900962,  0.04312528,
         -0.02775294,  0.02987519, -0.0228191 ,  0.02447735,
          0.02393228, -0.04386374]],

       [[-0.03817686, -0.02731646, -0.03528111,  0.03071573,
          0.03480065,  0.02348955, -0.00513406,  0.02617281,
         -0.02690274, -0.04256693],
        [-0.03195091,  0.0028404 ,  0.02852453,  0

In [20]:
embedded_doc[0]

array([   0, 7422, 3040, 8833, 2940], dtype=int32)